version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Environment variables for local development
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      SERVER_PORT: 3000
      JWT_SECRET: changeme
      NODE_ENV: development
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    # Mount source code for live-reload and preserve node_modules
    volumes:
      - ./server:/app
      - /app/node_modules
    # Use nodemon for automatic restart on file changes
    command: npm run dev

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "5173:80" # hostPort:containerPort, serves static site on 5173

volumes:
  db_data: {}
